import os 
from MDToolkit.data.objects import Topology, Frame 
from MDToolkit.paths import OUTPUT

atom_styles = {
    "atomic" : ["id", "type", "x", "y", "z"],
    "charge" : ["id", "type", "q", "x", "y", "z"],
    "full" : ["id", "mol", "type", "q", "x", "y", "z"]
    }

def write_lammps_data_file(frame : Frame, file_name = "output.data", file_path = OUTPUT, atom_style = "full"):
    '''
    '''
    file = os.path.join(file_path, file_name)

    with open(file, "w") as f:
        f.write("LAMMPS structure file generated by MDToolkit\n\n")

        f.write(f"{frame.num_atoms} atoms\n")
        if frame.topology.bonds is not None:
            f.write(f"{len(frame.topology.bonds)} bonds\n")
        if frame.topology.angles is not None:
            f.write(f"{len(frame.topology.angles)} angles\n")
        f.write(f"{len(frame.topology.type_mapping)} atom types\n")
        if frame.topology.bonds is not None:
            f.write(f"{frame.topology.get_bond_types()} bond types\n")
        if frame.topology.angles is not None:
            f.write(f"{frame.topology.get_angle_types()} angle types\n")
        f.write("\n")

        box = frame.box

        f.write(f"{box.mins[0]} {box.maxs[0]} xlo xhi\n")
        f.write(f"{box.mins[1]} {box.maxs[1]} ylo yhi\n")
        f.write(f"{box.mins[2]} {box.maxs[2]} zlo zhi\n")
        f.write("\n")

        f.write("Masses\n\n")
        for atom_type in sorted(frame.topology.type_mapping):
            element = frame.topology.type_mapping[atom_type]
            mass = frame.topology.elements_dict[element]["AtomicMass"]
            f.write(f"{atom_type} {mass} # {element}\n")
        f.write("\n")

        f.write(f"Atoms # {atom_style}\n\n")

        columns = atom_styles[atom_style]

        for i in range(frame.num_atoms):
            values = []
            for column in columns:
                if column == "id":
                    values.append(frame.ids[i])
                elif column == "mol":
                    values.append(frame.mol_ids[i])
                elif column == "type":
                    values.append(frame.types[i])
                elif column == "q":
                    values.append(
                        frame.topology.charges[frame.types[i]]
                    )
                elif column == "x":
                    values.append(frame.positions[i,0])
                elif column == "y":
                    values.append(frame.positions[i,1])
                elif column == "z":
                    values.append(frame.positions[i,2])
            f.write(" ".join(map(str, values)))
            f.write("\n")
    print(f"Successfully written file to " + file)