import os
from MDToolkit.data.objects import StructuredSystem

def write_pdb_file_from_StructuredSystem(StructuredSystem, file_name = "output.pdb", file_path="./Output", buffer_size = 8192):
    '''
    Writes a PDB file from a StructuredSystem object.

    INPUT:\n
    StructuredSystem (StructuredSystem): A StructuredSystem object containing the molecular system information to be written to the PDB file.
    file_name (str): The name of the PDB file to be created. Default is "output.pdb".
    file_path (str): The path where the PDB file will be saved. Default is "./Output".

    RETURNS:\n
    None: This function does not return anything. It writes a PDB file to the specified location.
    '''
    if not os.path.exists(file_path):
        os.makedirs(file_path)
    full_file_path = os.path.join(file_path, file_name)

    try:
      with open(full_file_path, 'w', buffering=buffer_size) as f:
          f.write("HEADER\n")
          f.write("REMARK  GENERATED BY MDToolkit\n")
          f.write("REMARK  FORMAT: ATOMTYPE ATOM_INDEX ATOM_SPECIES MOLECULE_NAME CHAIN_ID MOLECULE_INDEX X Y Z\n")
          for molecule in StructuredSystem.molecule_list:
              for atom in molecule.atoms:
                  entry_string = (
                      f"{atom.type:6}"      # columns 1-6
                      f"{atom.id:5} "       # columns 7-11
                      f"{atom.element:3}"   # atom name
                      f"{molecule.name:3} " # residue name
                      f"{atom.chain_id:3} " # chain identifier
                      f"{molecule.id:3}    "
                      f"{atom.position[0]:>8.3f}"
                      f"{atom.position[1]:>8.3f}"
                      f"{atom.position[2]:>8.3f}"
                  )

                  f.write(entry_string + "\n")
          f.write("END\n")
          print(f"PDB file successfully written to {full_file_path}")
    except Exception as e:
        print(f"Error occurred while writing PDB file: {e}")
