import os
from MDToolkit.data.objects import StructuredSystem

def write_pdb_file_from_StructuredSystem(structured_system, file_name="output.pdb", file_path="./Output"):
    '''
    Writes a PDB file from a StructuredSystem object.

    INPUT:\n
    structured_system (StructuredSystem): A StructuredSystem object containing the molecular system information.
    file_name (str): The name of the PDB file to be created. Default is "output.pdb".
    file_path (str): The path where the PDB file will be saved. Default is "./Output".

    RETURNS:\n
    None: This function does not return anything. It writes a PDB file to the specified location.
    '''
    if not os.path.exists(file_path):
        os.makedirs(file_path)
    full_file_path = os.path.join(file_path, file_name)

    try:
        with open(full_file_path, 'w') as f:
            f.write("HEADER\n")
            f.write("REMARK  GENERATED BY MDToolkit\n")
            f.write("REMARK  COLS  1- 6: RECORD TYPE (ATOM/HETATM)\n")
            f.write("REMARK  COLS  7-11: ATOM SERIAL NUMBER\n")
            f.write("REMARK  COLS 13-16: ATOM NAME / ELEMENT\n")
            f.write("REMARK  COLS 17   : ALTERNATE LOCATION INDICATOR (BLANK)\n")
            f.write("REMARK  COLS 18-20: RESIDUE NAME\n")
            f.write("REMARK  COLS 22   : CHAIN IDENTIFIER\n")
            f.write("REMARK  COLS 23-26: RESIDUE SEQUENCE NUMBER\n")
            f.write("REMARK  COLS 27   : INSERTION CODE (BLANK)\n")
            f.write("REMARK  COLS 31-38: X ORTHOGONAL COORDINATE (ANGSTROMS)\n")
            f.write("REMARK  COLS 39-46: Y ORTHOGONAL COORDINATE (ANGSTROMS)\n")
            f.write("REMARK  COLS 47-54: Z ORTHOGONAL COORDINATE (ANGSTROMS)\n")
            f.write("REMARK  COLS 55-60: OCCUPANCY (DEFAULT 1.00)\n")
            f.write("REMARK  COLS 61-66: TEMPERATURE FACTOR (DEFAULT 0.00)\n")
            f.write("REMARK  COLS 77-78: ELEMENT SYMBOL\n")
            f.write("REMARK  COLS 79-80: CHARGE (BLANK)\n")

            for molecule in structured_system.molecule_list:
                for atom in molecule.atoms:
                    record_name  = atom.type.upper().ljust(6)          # cols  1-6:  record name, left-justified
                    atom_serial  = f"{atom.id:5d}"                     # cols  7-11: atom serial number, right-justified
                    blank_12     = " "                                  # col   12:   blank

                    element_str  = atom.element.strip().upper()        # cols 13-16: atom name
                    if len(element_str) == 1:
                        atom_name = f" {element_str:<3s}"              #   1-char: blank in col 13, symbol in col 14
                    else:
                        atom_name = f"{element_str:<4s}"               #   2-char: symbol starts in col 13

                    alt_loc      = " "                                  # col   17:   alternate location indicator (blank)
                    res_name     = f"{molecule.name[:3]:>3s}"               # cols 18-20: residue name, right-justified
                    blank_21     = " "                                  # col   21:   blank
                    chain_id     = f"{str(atom.chain_id)[0]:1s}"        # col   22:   chain identifier, single char
                    res_seq      = f"{molecule.id:4d}"                  # cols 23-26: residue sequence number, right-justified
                    icode        = " "                                  # col   27:   code for insertion of residues (blank)
                    blanks_28_30 = "   "                                # cols 28-30: blank
                    x            = f"{atom.position[0]:8.3f}"          # cols 31-38: X coordinate
                    y            = f"{atom.position[1]:8.3f}"          # cols 39-46: Y coordinate
                    z            = f"{atom.position[2]:8.3f}"          # cols 47-54: Z coordinate
                    occupancy    = f"{1.00:6.2f}"                       # cols 55-60: occupancy, default 1.00
                    temp_factor  = f"{0.00:6.2f}"                       # cols 61-66: temperature factor, default 0.00
                    blanks_67_76 = "          "                         # cols 67-76: blank
                    element      = f"{atom.element.strip():>2s}"        # cols 77-78: element symbol, right-justified
                    charge       = "  "                                 # cols 79-80: charge (blank)

                    entry_string = (
                        record_name   # 1-6
                        + atom_serial  # 7-11
                        + blank_12     # 12
                        + atom_name    # 13-16
                        + alt_loc      # 17
                        + res_name     # 18-20
                        + blank_21     # 21
                        + chain_id     # 22
                        + res_seq      # 23-26
                        + icode        # 27
                        + blanks_28_30 # 28-30
                        + x            # 31-38
                        + y            # 39-46
                        + z            # 47-54
                        + occupancy    # 55-60
                        + temp_factor  # 61-66
                        + blanks_67_76 # 67-76
                        + element      # 77-78
                        + charge       # 79-80
                    )

                    f.write(entry_string + "\n")

            f.write("END\n")
            print(f"PDB file successfully written to {full_file_path}")

    except Exception as e:
        print(f"Error occurred while writing PDB file: {e}")
