[build-system]
requires = [
    "scikit-build-core>=0.10",
    "pybind11",
]
build-backend = "scikit_build_core.build"

[project]
name = "MDToolkit"
version = "0.1.0"
description = "Molecular dynamics toolkit"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.scikit-build]
wheel.packages = ["MDToolkit"]

[tool.scikit-build.editable]
mode = "redirect"