from MDToolkit.utils.structure_file_utils import elements_and_stoichiometries_to_molar_mass, molecular_formula_to_elements_and_stoichiometries

elements, stoichs = molecular_formula_to_elements_and_stoichiometries("KCl")

print(elements_and_stoichiometries_to_molar_mass(elements, stoichs))